# This workflow will run any files matching "tests/*_test.py" using the Python
# unittest module.
# The module is invoked by the coverage module, which generates a test coverage
# report called ".coveragerc", which is sent to coveralls.io as the final step.

name: Run Python unit tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp backoff coverage coveralls websockets yarl
      - name: Run tests
        run: |
          python -m coverage run --source auraxium/ -m unittest discover -p *_test.py tests/
      - name: Upload code coverage analysis
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          python -m coveralls
